"""initial schema with monthly token fields

Revision ID: edd3ef9e3f62
Revises: 
Create Date: 2026-03-12 08:49:53.768666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd3ef9e3f62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tokens_optimized', sa.Integer(), nullable=False),
    sa.Column('tokens_saved', sa.Integer(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('first_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('monthly_tokens_used', sa.Integer(), nullable=False),
    sa.Column('monthly_reset_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('optimization_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=50), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('original_tokens', sa.Integer(), nullable=False),
    sa.Column('optimized_tokens', sa.Integer(), nullable=False),
    sa.Column('savings', sa.Integer(), nullable=False),
    sa.Column('savings_percentage', sa.Float(), nullable=False),
    sa.Column('technique', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opt_logs_key_created', 'optimization_logs', ['key_hash', 'created_at'], unique=False)
    op.create_index(op.f('ix_optimization_logs_key_hash'), 'optimization_logs', ['key_hash'], unique=False)
    op.create_index(op.f('ix_optimization_logs_request_id'), 'optimization_logs', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimization_logs_request_id'), table_name='optimization_logs')
    op.drop_index(op.f('ix_optimization_logs_key_hash'), table_name='optimization_logs')
    op.drop_index('ix_opt_logs_key_created', table_name='optimization_logs')
    op.drop_table('optimization_logs')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
