import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './tests/e2e',
  timeout: 60000,
  retries: 1,
  use: {
    baseURL: process.env.TEST_BASE_URL || 'http://localhost:3000',
    screenshot: 'only-on-failure',
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'smoke',
      testMatch: ['homepage.spec.ts', 'full-journey.spec.ts'],
    },
    {
      name: 'individual-journey',
      testMatch: 'individual-journey.spec.ts',
    },
    {
      name: 'team-journey',
      testMatch: 'team-journey.spec.ts',
    },
    {
      name: 'load-10x',
      testMatch: 'load-10x-journey.spec.ts',
      timeout: 120000,
    },
    {
      name: 'load-100x',
      testMatch: 'load-100x-journey.spec.ts',
      timeout: 300000,
    },
    {
      name: 'qa-navigation',
      testDir: './qa-system/specs',
      testMatch: '01-navigation.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-intent',
      testDir: './qa-system/specs',
      testMatch: '02-intent.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-accessibility',
      testDir: './qa-system/specs',
      testMatch: '03-accessibility.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-forms',
      testDir: './qa-system/specs',
      testMatch: '04-forms.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-visual',
      testDir: './qa-system/specs',
      testMatch: '05-visual.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-mobile',
      testDir: './qa-system/specs',
      testMatch: '06-mobile.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-seo',
      testDir: './qa-system/specs',
      testMatch: '07-seo-meta.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-security',
      testDir: './qa-system/specs',
      testMatch: '08-security.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-content',
      testDir: './qa-system/specs',
      testMatch: '09-content.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-performance',
      testDir: './qa-system/specs',
      testMatch: '10-performance.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-auth-crawler',
      testDir: './qa-system/specs',
      testMatch: '12-authenticated-crawler.spec.ts',
      timeout: 60000,
    },
    {
      name: 'qa-destination-crawler',
      testDir: './qa-system/specs',
      testMatch: '11-destination-crawler.spec.ts',
      timeout: 60000,
    },
    {
      name: 'qa-flow-crawler',
      testDir: './qa-system/specs',
      testMatch: '13-flow-crawler.spec.ts',
      timeout: 120000,
    },
    // ─── Exhaustive Suite (specs 14-29) ─────────────────────────
    {
      name: 'qa-stripe',
      testDir: './qa-system/specs',
      testMatch: '14-stripe-checkout.spec.ts',
      timeout: 60000,
    },
    {
      name: 'qa-email',
      testDir: './qa-system/specs',
      testMatch: '15-email-delivery.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-slo',
      testDir: './qa-system/specs',
      testMatch: '16-api-slo.spec.ts',
      timeout: 120000,
    },
    {
      name: 'qa-webhook',
      testDir: './qa-system/specs',
      testMatch: '17-webhook-resilience.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-session',
      testDir: './qa-system/specs',
      testMatch: '18-session-expiry.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-concurrent',
      testDir: './qa-system/specs',
      testMatch: '19-concurrent-mutations.spec.ts',
      timeout: 60000,
    },
    {
      name: 'qa-freshness',
      testDir: './qa-system/specs',
      testMatch: '20-content-freshness.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-sitemap',
      testDir: './qa-system/specs',
      testMatch: '21-sitemap-robots.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-fuzz',
      testDir: './qa-system/specs',
      testMatch: '22-fuzz-testing.spec.ts',
      timeout: 60000,
    },
    {
      name: 'qa-offline',
      testDir: './qa-system/specs',
      testMatch: '23-offline-degraded.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-deps',
      testDir: './qa-system/specs',
      testMatch: '24-dependency-audit.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-lighthouse',
      testDir: './qa-system/specs',
      testMatch: '25-lighthouse.spec.ts',
      timeout: 120000,
    },
    {
      name: 'qa-cross-browser',
      testDir: './qa-system/specs',
      testMatch: '26-cross-browser.spec.ts',
      timeout: 60000,
    },
    {
      name: 'qa-migrations',
      testDir: './qa-system/specs',
      testMatch: '27-database-migration.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-canary',
      testDir: './qa-system/specs',
      testMatch: '28-canary-smoke.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-rbac',
      testDir: './qa-system/specs',
      testMatch: '29-rbac-tier-enforcement.spec.ts',
      timeout: 60000,
      // Single worker so the module-level user cache in
      // 29-rbac-tier-enforcement.spec.ts is shared across all tests.
      // Without this each worker triggers its own signup and trips the
      // 3-per-IP-per-hour signup rate limiter (rate-limit.ts:30).
      fullyParallel: false,
      workers: 1,
    },
    {
      name: 'qa-council-fixes',
      testDir: './qa-system/specs',
      testMatch: '30-council-fixes.spec.ts',
      timeout: 60000,
    },
    {
      name: 'qa-post-action',
      testDir: './qa-system/specs',
      testMatch: '31-post-action-destinations.spec.ts',
      timeout: 90000,
    },
    // ─── Gap Closure Suite (specs 33-39) ──────────────────────
    {
      name: 'qa-stripe-live',
      testDir: './qa-system/specs',
      testMatch: '33-stripe-live-test.spec.ts',
      timeout: 60000,
    },
    {
      name: 'qa-support-workflow',
      testDir: './qa-system/specs',
      testMatch: '34-support-workflow.spec.ts',
      timeout: 60000,
    },
    {
      name: 'qa-ops-health',
      testDir: './qa-system/specs',
      testMatch: '35-operations-health.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-enterprise',
      testDir: './qa-system/specs',
      testMatch: '36-enterprise-readiness.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-sustained-load',
      testDir: './qa-system/specs',
      testMatch: '37-sustained-load.spec.ts',
      timeout: 300000,
    },
    {
      name: 'qa-attack-chains',
      testDir: './qa-system/specs',
      testMatch: '38-attack-chains.spec.ts',
      timeout: 60000,
    },
    {
      name: 'qa-sdk-live',
      testDir: './qa-system/specs',
      testMatch: '39-sdk-live-integration.spec.ts',
      timeout: 60000,
    },
    // ─── 99% Coverage Suite (specs 40-48) ─────────────────────
    {
      name: 'qa-a11y-deep',
      testDir: './qa-system/specs',
      testMatch: '40-accessibility-deep.spec.ts',
      timeout: 60000,
    },
    {
      name: 'qa-analytics',
      testDir: './qa-system/specs',
      testMatch: '41-analytics-completeness.spec.ts',
      timeout: 60000,
    },
    {
      name: 'qa-perf-ext',
      testDir: './qa-system/specs',
      testMatch: '42-performance-extended.spec.ts',
      timeout: 300000,
    },
    {
      name: 'qa-stripe-e2e',
      testDir: './qa-system/specs',
      testMatch: '43-stripe-checkout-e2e.spec.ts',
      timeout: 60000,
    },
    {
      name: 'qa-email-inbox',
      testDir: './qa-system/specs',
      testMatch: '44-email-inbox-verification.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-security-scan',
      testDir: './qa-system/specs',
      testMatch: '45-security-scan.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-oauth',
      testDir: './qa-system/specs',
      testMatch: '46-oauth-flow.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-observability',
      testDir: './qa-system/specs',
      testMatch: '47-observability-verification.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-sdk-publish',
      testDir: './qa-system/specs',
      testMatch: '48-sdk-publish.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-key-sharing',
      testDir: './qa-system/specs',
      testMatch: '50-key-sharing-detection.spec.ts',
      timeout: 60000,
    },
    {
      name: 'qa-optimization-accuracy',
      testDir: './qa-system/specs',
      testMatch: '49-optimization-accuracy.spec.ts',
      timeout: 60000,
    },
    {
      name: 'qa-business-fixes',
      testDir: './qa-system/specs',
      testMatch: '32-business-council-fixes.spec.ts',
      timeout: 60000,
    },
    // ─── Final 15 Gap Closure (specs 51-54) ─────────────────
    {
      name: 'qa-live-behavior',
      testDir: './qa-system/specs',
      testMatch: '51-live-behavior-verification.spec.ts',
      timeout: 120000,
    },
    {
      name: 'qa-missing-scenarios',
      testDir: './qa-system/specs',
      testMatch: '52-missing-scenarios.spec.ts',
      timeout: 120000,
    },
    {
      name: 'qa-cookie-security',
      testDir: './qa-system/specs',
      testMatch: '53-cookie-security.spec.ts',
      timeout: 60000,
    },
    {
      name: 'qa-browser-resilience',
      testDir: './qa-system/specs',
      testMatch: '54-browser-resilience.spec.ts',
      timeout: 60000,
    },
    // ─── Zero Gaps (specs 55-57) ───────────────────────────────
    {
      name: 'qa-stripe-real',
      testDir: './qa-system/specs',
      testMatch: '55-stripe-real-checkout.spec.ts',
      timeout: 60000,
    },
    {
      name: 'qa-resend-email',
      testDir: './qa-system/specs',
      testMatch: '56-resend-email-delivery.spec.ts',
      timeout: 60000,
    },
    {
      name: 'qa-edge-final',
      testDir: './qa-system/specs',
      testMatch: '57-edge-cases-final.spec.ts',
      timeout: 60000,
    },
    {
      name: 'qa-pricing-source',
      testDir: './qa-system/specs',
      testMatch: '58-pricing-single-source.spec.ts',
      timeout: 30000,
    },
    {
      name: 'qa-system',
      testDir: './qa-system/specs',
      testMatch: '*.spec.ts',
      timeout: 120000,
    },
    // ─── Product QA Agents ───────────────────────────────────────
    {
      name: 'product-api-contract',
      testDir: './qa-system/product-agents',
      testMatch: '01-api-contract.spec.ts',
      timeout: 30000,
    },
    {
      name: 'product-quality',
      testDir: './qa-system/product-agents',
      testMatch: '02-optimization-quality.spec.ts',
      timeout: 30000,
    },
    {
      name: 'product-npm-sdk',
      testDir: './qa-system/product-agents',
      testMatch: '03-npm-sdk.spec.ts',
      timeout: 120000,
    },
    {
      name: 'product-python-sdk',
      testDir: './qa-system/product-agents',
      testMatch: '04-python-sdk.spec.ts',
      timeout: 30000,
    },
    {
      name: 'product-key-lifecycle',
      testDir: './qa-system/product-agents',
      testMatch: '05-key-lifecycle.spec.ts',
      timeout: 30000,
    },
    {
      name: 'product-cross',
      testDir: './qa-system/product-agents',
      testMatch: '06-cross-product.spec.ts',
      timeout: 30000,
    },
    {
      name: 'product-ide-plugins',
      testDir: './qa-system/product-agents',
      testMatch: '07-ide-plugins.spec.ts',
      timeout: 30000,
    },
    {
      name: 'product-integration',
      testDir: './qa-system/product-agents',
      testMatch: '08-integration.spec.ts',
      timeout: 30000,
    },
    {
      name: 'product-all',
      testDir: './qa-system/product-agents',
      testMatch: '*.spec.ts',
      timeout: 120000,
    },
    // ─── Launch Day Simulation ─────────────────────────────────────────
    {
      name: 'launch-day-simulation',
      testDir: './tests/launch-day',
      testMatch: 'launch-day-simulation.spec.ts',
      timeout: 300000,
      use: {
        baseURL: process.env.TEST_BASE_URL || 'https://www.fortress-optimizer.com',
        screenshot: 'on',
        trace: 'on',
        video: 'on',
      },
    },
  ],
});
